- alert: HighErrorRate
  expr: rate(istio_requests_total{response_code=~"5.."}[1m]) > 0.1
  for: 1m
  labels:
    severity: critical
  annotations:
    summary: "High error rate"
    description: "More than 10% of requests are failing"
